# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.11.0
    hooks:
    - id: black
  - repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        stages: [commit]
        types: [python]
        entry: pytest -v -s
        language: system
        pass_filenames: false
        always_run: true
    -   id: pytest-check-coverage
        name: pytest-coverage
        stages: [ commit ]
        types: [ python ]
        entry: pytest --cov=src
        language: system
        pass_filenames: false
        always_run: true
